# Generated by Django 3.1.3 on 2020-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='myrating',
            field=models.IntegerField(default=0),
        ),
    ]
