# Generated by Django 3.0.7 on 2020-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totp',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
