# Generated by Django 3.1.3 on 2020-12-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user', models.TextField()),
                ('review', models.TextField()),
                ('image', models.TextField(default='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.TextField()),
                ('offer', models.TextField(max_length=5)),
                ('availability', models.TextField(max_length=3)),
                ('categories', models.TextField()),
            ],
        ),
    ]
