# Generated by Django 3.1.3 on 2020-12-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20201212_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartproduct',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('productobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
