# Generated by Django 3.1.3 on 2020-12-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartproduct',
            fields=[
                ('id', models.AutoField(default=1,auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productobj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.product')),
            ],
        ),
    ]
