# Generated by Django 3.1.3 on 2020-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='serial',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
