# Generated by Django 3.1.3 on 2020-12-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('cart', '0003_auto_20201209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='productobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.product', unique=True),
        ),
    ]
