# Generated by Django 3.1.3 on 2020-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201209_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
