# Generated by Django 3.1.3 on 2020-12-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('cart', '0005_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='productobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.product'),
        ),
    ]
