# Generated by Django 3.1.3 on 2020-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201209_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='serial',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
